import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import React from 'react'

const Announcement = () => {
  const router = useRouter()
  const { id } = router.query

  const fetcher = (url, queryParams = '?limit=100') =>
    fetch(`${url}${queryParams}`).then((res) => res.json())

  const { data } = useSWR(`/api/announcements/${id}`, fetcher)

  if (!data?.data) {
    return <div>Loading</div>
  } else {
    data.data.id = data.id
  }

  const style = {
    body: {
      fontSize: '16px',
      fontFamily: 'Arial, sans-serif',
    },
    h1: {
      marginTop: '0',
      marginBottom: '1rem',
      fontSize: '2em',
      lineHeight: '1.2',
    },
    h2:{
     marginTop:'2rem',
     marginBottom:'1rem',
     fontSize:'1.5em',
     lineHeight:'1.3'
  },
  h3:{marginTop : '.5 rem' ,
       marginBottom :'.75 rem' ,
       fontSize :'1 em ',
        lineHeight :

                  .9 ,
  },

  h4:{marginTop :'.25 rem' ,
       marginBottom :'.5 rem',
       fontSize :'0.875 em ',
       lineHeight :
                  .9,
  },
  p:{marginTop :
            "0",
  marginBottom:"" },

  ul:{
  paddingLeft:
         "20px",
  listStyleType:"disc"
  },

  ol:{
  paddingLeft:"30px",

  counterReset :"numberedListCounter",
  "& li":{ counterIncrement :"numberedListCounter"},
  "& li:before":{
   content :"counter(numberedListCounter) '.'",
   position :"absolute", left:"-30px"}
  },


  a:{
  color:'#007bff',
  textDecoration:'underline'},

  "a:hover": { textDecoration:"none !important"},

  };

  return (
    <div>
      <Head>
        <title>{data?.data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-8 mx-auto my-8 bg-white border-b shadow-md sm:rounded-lg dark:bg-gray-800/95 dark:border-gray-700">
        <h1 className=''>{data?.data?.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: data?.data?.message}} style={{style}}></div>

      </div>

    </div>
  )
}

export default Announcement
