import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import React from 'react'

const Location = () => {
  const router = useRouter()
  const { id } = router.query

  const fetcher = (url, queryParams = '?limit=100') =>
    fetch(`${url}${queryParams}`).then((res) => res.json())

  const { data } = useSWR(`/api/announcements/${id}`, fetcher)

  if (!data?.data) {
    return <div>Loading</div>
  } else {
    data.data.id = data.id
  }

  return (
    <div>
      <Head>
        <title>{data?.data?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-lg p-8 mx-auto my-8 bg-white border-b shadow-md sm:rounded-lg dark:bg-gray-800/95 dark:border-gray-700">
        <h1>{data.data.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: data.data.message}}></div>

      </div>

      <footer></footer>
    </div>
  )
}

export default Location
